### ISSUE TITLE
Snap card text container don't fill the width

### ISSUE THREAD

**Issue by BrunoBiagioniNeto** [Telefonica/mistica-design#1005]
### Describe the bug
En Figma, cuando inserto textos, están limitados en ancho fijo, el texto no sigue el ancho del componente.

### To Reproduce
1. agregar componente SnapCard en figma.
2. introduzca un texto grande.
3. Observe lo que sucede, el texto no aumenta de ancho.

### Expected behavior
El texto debe aumentar de ancho para seguir el contenedor de la tarjeta.

### Details (please complete the following information):

- Mobile 
- Vivo

Component name: Snap Card

### Figma file
https://www.figma.com/file/4MTA32XpZ1RPvHAy7UuwGr/Snap-Card-Bug-Text?node-id=0%3A1&t=lP67r3JllME4rEmR-1

### Additional context
N/A

**Comment by yceballost** [comment]
thanks to contribute to Mística reporting this bug! 🥰

the fix is in review [here](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/55t0mdT6iXer8GxxCarelO/M%C3%ADstica-Mobile?t=iCJBygIC4qbhk9ns-1). When the review will be complete we will release a new version (probably tomorrow in the morning GMT+1)
