### ISSUE TITLE
Icon Sizes | Theme Context

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1669]
### Describe the bug

Quando alteramos o Theme Context para Inverse no tema Vivo New, alguns ícones não estão atribuindo a o token de cor definido para cada contexto.

### What libraries are you seeing the problem on?

Vivo Library

### Steps to reproduce

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Estudos?type=design&node-id=2410%3A523&mode=design&t=7BAY3rIyJ8VWfhIU-1

### Expected behavior

Ao alterar para o Theme Context = Inverse, o token atribuído deve ser "inverse".

**Comment by aweell** [comment]
Hi @annefranca,

The issue seems to be mostly related to themer rather than the component iconSizes

In order to achieve icons in inverse in another theme the steps should be

1. Change the default icon to inverse
2. Change the size if needed
3. Replace the icon with the icon you want to use
4. Use themer

following that steps should ensure all icons behave as expected
