### ISSUE TITLE
Align content in Accordion when asset is visible

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1755]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1738

<div type='discussions-op-text'>

<sup>Originally posted by **msagrilo** April 19, 2024</sup>
### Goal

O objetivo é mudar o alinhamento do texto do accordion, quando ele está aberto.

### Context

Quando temos a versão grouped accordion, a hierarquia de leitura fica ruim.

### Impact

Trazer um conforto visual na leitura.

### Discussion Questions

Fiz uma mini poc para ajudar na percepção.

### Do you have a visual proposal?

https://www.figma.com/file/12wZyia8Y0vbx8fFpiP9Pm/Accordion-Evolution?type=design&node-id=2015%3A550&mode=design&t=BsB94RXFGdFilS5N-1</div>

### Tasks 

- [x] [Update specs](https://www.figma.com/design/KDxPjcTXq2NCvQZjb4FXgi/branch/AzWBNpHWqcI64ZL5GzDy5i/%F0%9F%94%B8-Accordion-Specs?m=auto&t=lp3phi2eagohDjlQ-1)
- [ ] Update documentation
- [ ] Web ticket

**Comment by aweell** [comment]
There are two aspects that are concerning about this approach.

1. The size of the asset could compromise the legibility of the text in small devices
2. Since the asset size is something that we cannot control, align the asset when the title is centered in the header area and at the same time reserve that space in the left of the content panel is something tricky. At least in Figma i couldn't find a way to solve this problem.

Here's the branch with the changes: https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/vzs1YCZ3yMTj0tKyc8KlvG/M%C3%ADstica-Mobile?m=auto&node-id=25050-313&t=SCgyFq5coBP9qwmU-1

**Comment by yceballost** [comment]
Reason: https://github.com/Telefonica/mistica-design/discussions/1738#discussioncomment-9839204
