### ISSUE TITLE
Componentes Community de Desktop estão usando componentes e presets de texto de Mobile

### ISSUE THREAD

**Issue by BiancaMach** [Telefonica/mistica-design#1843]
### Describe the bug

Os componentes de community para Desktop estão utilizando text presets e alguns componentes de Mobile.

Componentes relatados:

<img width="738" alt="Screenshot 2024-08-02 at 18 11 57" src="https://github.com/user-attachments/assets/a63f627d-7789-4244-ac9b-2e4fbb11b64a"><br>
<img width="823" alt="Screenshot 2024-08-02 at 18 12 04" src="https://github.com/user-attachments/assets/0e1dadf5-c808-44d4-a9d9-d74c67741604"><br>
<img width="462" alt="Screenshot 2024-08-02 at 18 12 13" src="https://github.com/user-attachments/assets/c562956c-2351-444d-8a5e-55e818ede029"><br>
<img width="452" alt="Screenshot 2024-08-02 at 18 12 20" src="https://github.com/user-attachments/assets/22e9c023-c4bd-4f1e-a0d0-da8e75c815af"><br>
<img width="583" alt="Screenshot 2024-08-02 at 18 12 29" src="https://github.com/user-attachments/assets/1d00f992-39b2-4f39-bb0f-0f0e1ee55c99"><br>
<img width="515" alt="Screenshot 2024-08-02 at 18 12 37" src="https://github.com/user-attachments/assets/ebdd3986-aa92-4de8-b69b-29e16d2cab58"><br>
<img width="564" alt="Screenshot 2024-08-02 at 18 13 16" src="https://github.com/user-attachments/assets/a29cc24f-d74e-4085-9c01-8e3d864c3733">

### What libraries are you seeing the problem on?

Desktop Library

### Steps to reproduce

N/D

### Expected behavior

Os elementos e presets de texto utilizados nos componentes de community deveriam ser os de Desktop.

**Comment by aweell** [comment]
Hello @BiancaMach we have add the account "Design Ops Vivo" as reviewer of the changes

**Comment by BiancaMach** [comment]
thank you @aweell, I saw the branch but i didn't notice the changes. Is it done already?

**Comment by BiancaMach** [comment]
@aweell I saw the branch but I didn't notice the changes. Is it done?

**Comment by aweell** [comment]
Hello @BiancaMach, updating button links in this branch is breaking change: 

https://www.figma.com/design/luifboVkvANqe3VABq0ERb?node-id=10815-10696#928982767

This is coming from: https://teams.microsoft.com/l/message/19:meeting_M2U4YzVmMTQtOWQ0OS00Y2RiLWI0OWUtZDU0ZGU4NzA0MTA5@thread.v2/1711967489221?context=%7B%22contextType%22%3A%22chat%22%7D

The advanced data card in desktop has the following inserts this year, I think is ok to do this breaking.

![Screenshot 2024-09-02 at 11 35 48](https://github.com/user-attachments/assets/30ad5a25-40e5-45cc-886b-a2d8a2268bfd)

But just to let you know that updating that buttons will potentially override all texts in the button links used in the footer of de advanced data card.

If you're okay with the changes, this will included in [15.0.0](https://github.com/Telefonica/mistica-design/milestone/55) version and released by the end of the month.

**Comment by BiancaMach** [comment]
@aweell Understood. I think we should wait to change that. If we change the "Tag" component to the desktop "Tag" are we gonna have the same problem?

**Comment by aweell** [comment]
> @aweell Understood. I think we should wait to change that. 

Perfect, I'll revert the changes to avoid publishing this change in the next release.

To give you more context about this problem, my guess here is that [when the buttons were updated to split them in different components](https://github.com/Telefonica/mistica-design/issues/1336), some instances of the button somehow didn't update correctly, and now making the swap is causing a breaking change.

If i can give you a piece of advice making breaking change, is always hard to know when to make them, but if you wait too much more people will be using the "corrupted" instance and more people will be affected later. If you still want to wait, this breaking can go inside 16.0.0 (End of year).

> If we change the "Tag" component to the desktop "Tag" are we gonna have the same problem?

No, in the tag component this is not an issue, is specifically affecting the button because the internal structure of the current instance (outdated component) is not near similar to the new buttonLink structure, so when swaping the instance Figma doesn't preserve the content.

You can test the tag just swaping a mobile tag with a content override with a desktop tag, the content should remain changed instead of be overwritten.

**Comment by BiancaMach** [comment]
@aweell Perfect. Thank you for all the information. We'll plan this change soon. Did you see the other components I commented on the Figma branch? Display Data Card (D) and Display Media Card (D) are also with the mobile presets.

**Comment by aweell** [comment]
> @aweell Perfect. Thank you for all the information. We'll plan this change soon. Did you see the other components I commented on the Figma branch? Display Data Card (D) and Display Media Card (D) are also with the mobile presets.

We will create another branch for this change, in order to no mix changes

Issue: https://github.com/Telefonica/mistica-design/issues/1885
