### ISSUE TITLE
→ Text constant project | Create definition/specs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#822]
Demo:

https://github.com/aweell/mistica-tokens

**Comment by aweell** [comment]
## Token structure definition

![Screenshot 2022-10-14 at 11 08 51](https://user-images.githubusercontent.com/44420072/195808993-c0683793-32ca-49c2-a7b8-2005f51ee678.png)



## Global tokens

The global tokens are the color constants equivalence in the typography world.

### Font size

```
// JSON Example

"fontSize": { 
   "1": {"$value": "0.75rem" },
   ...
}
```


Token | Value (px) [Root: 16px] | Value (rem)
-- | -- | --
`fontSize13` | 64 | 4
`fontSize12` | 56 | 3.5
`fontSize11` | 48 | 3
`fontSize10` | 40 | 2.5
`fontSize9` | 32 | 2
`fontSize8` | 28 | 1.75
`fontSize7` | 24 | 1.5
`fontSize6` | 22 | 1.375
`fontSize5` | 20 | 1.25
`fontSize4` | 18 | 1.125
`fontSize3` | 16 | 1
`fontSize2` | 14 | 0.875
`fontSize1` | 12 | 0.75

### Line height

```
// JSON Example

"lineHeight": { 
   "1": {"$value": "1em" },
   ...
}
```


#### Current

Name | Font size / Line height (mobile) | Multiplier (mobile) | Font size / Line height (desktop) | Multiplier (desktop)
-- | -- | -- | -- | -- 
text-preset-10 | 32/40 | 1.25 | 64/72 | 1.125
text-preset-9 | 32/40 | 1.25 | 56/64 | 1.1428...❗
text-preset-8 | 32/40 | 1.25 | 48/56 | 1.1666...❗
text-preset-7 | 28/32 | 1.1428... ❗| 40/48 | 1.2
text-preset-6 | 24/32 | 1.3333... ❗| 32/40 | 1.25
text-preset-5 | 22/24 | 1.0909... ❗| 28/32 | 1.1428...❗
text-preset-4 | 18/24 | 1.3333... ❗| 20/28 | 1.4
text-preset-3 | 16/24 | 1.5 | 18/24 | 1.333 ❗
text-preset-2 | 14/20 | 1.4285... ❗| 16/24 | 1.5
text-preset-1 | 12/16 | 1.3333... ❗| 14/20 | 1.4285..❗

#### Proposal

##### Core values

Token |  Value (em)
-- | -- 
`lineHeight1` | 1.5
`lineHeight2` | 1.375
`lineHeight3` |  1.25

##### Alias values

```
"line-height-preset": {
    "desktop": {
      "1": { "type": "font", "value": "{core.line-height.1}" },
      "2": { "type": "font", "value": "{core.line-height.1}" },
      "3": { "type": "font", "value": "{core.line-height.1}" },
      "4": { "type": "font", "value": "{core.line-height.1}" },
      "5": { "type": "font", "value": "{core.line-height.1}" },
      "6": { "type": "font", "value": "{core.line-height.2}" },
      "7": { "type": "font", "value": "{core.line-height.2}" },
      "8": { "type": "font", "value": "{core.line-height.3}" },
      "9": { "type": "font", "value": "{core.line-height.3}" },
      "10": { "type": "font", "value": "{core.line-height.3}" }
    },
    "mobile": {
      "1": { "type": "font", "value": "{core.line-height.1}" },
      "2": { "type": "font", "value": "{core.line-height.1}" },
      "3": { "type": "font", "value": "{core.line-height.1}" },
      "4": { "type": "font", "value": "{core.line-height.1}" },
      "5": { "type": "font", "value": "{core.line-height.1}" },
      "6": { "type": "font", "value": "{core.line-height.1}" },
      "7": { "type": "font", "value": "{core.line-height.1}" },
      "8": { "type": "font", "value": "{core.line-height.2}" },
      "9": { "type": "font", "value": "{core.line-height.2}" },
      "10": { "type": "font", "value": "{core.line-height.2}" }
    }
  }
```

### Weight

Brands like movistar have different weights in text-preset 5 and above. Only those text preset have an alias token.

#### Core tokens


Token | Value 
-- | -- 
`fontWeight4` | 700 
`fontWeight3` | 500 
`fontWeight2` | 400
`fontWeight1` | 300 

#### Alias tokens

```
"weight-preset": {
    "5": {
      "description": "Font weight",
      "type": "font",
      "value": "{core.font-weight.1}"
    },
    "6": {
      "description": "Font weight",
      "type": "font",
      "value": "{core.font-weight.1}"
    },
    "7": {
      "type": "font",
      "value": "{core.font-weight.1}"
    },
    "8": {
      "description": "Font weight",
      "type": "font",
      "value": "{core.font-weight.1}"
    },
    "9": {
      "description": "Font weight",
      "type": "font",
      "value": "{core.font-weight.1}"
    },
    "10": {
      "description": "Font weight",
      "type": "font",
      "value": "{core.font-weight.1}"
    }
  },
```



### Other possible properties to cover

* `font-family`: defined by brand (could be interesting to include serif and sans serif?)
* `letter-spacing`: define fixed values for specific text component styles


### Not considered

* `font-style`: since the tokens will be a direct representation of the CSS values available I don't see value in bringing this abstraction here. The same applies to `text-decoration` and `text-transform`
